import React,{useEffect,useRef,useState} from 'react';
import {Camera,Upload,Check,ScanFace,ChevronRight,ShieldCheck,LoaderCircle,ArrowLeft,ArrowRight,ArrowUp,ArrowDown} from 'lucide-react';
import {detect,imageFile} from './vision';import {api} from './api';import {config} from './config';import type {Face} from './store';
export function Entry({children}:{children:React.ReactNode}){const[teacher,setTeacher]=useState(false),[checking,setChecking]=useState(true),[login,setLogin]=useState(false),[password,setPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
useEffect(()=>{api('auth').then(r=>setTeacher(r.teacher)).catch(()=>{}).finally(()=>setChecking(false))},[]);
if(checking)return <div className="loading"><LoaderCircle className="spin"/>Opening EigenRoll…</div>;
if(teacher)return <><button className="signout" onClick={async()=>{await api('auth','DELETE');location.reload()}}>Teacher sign out</button>{children}</>;
return <div className="entry"><header><a className="brand" href="/"><span className="brand-icon"><ScanFace/></span>eigenroll<span className="brand-dot">.</span></a><button onClick={()=>{setLogin(!login);setError('')}}>{login?'Student registration':'Teacher sign in'}</button></header>{login?<div className="entry-card panel"><div className="eyebrow">TEACHER WORKSPACE</div><h1>Welcome back.</h1><p>Use your private teacher access key to manage registrations and attendance.</p><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await api('auth','POST',{password});setPassword('');setTeacher(true)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}><label>Teacher access key<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required/></label>{error&&<p className="alert error" role="alert">{error}</p>}<button className="primary full" disabled={busy}>{busy?'Signing in…':'Open teacher workspace'}</button></form></div>:<Enrollment/>}<footer>EigenRoll · PCA + LDA attendance · Registration with your permission</footer></div>
}
function Enrollment(){const invite=new URLSearchParams(location.search).get('invite')??config.defaultInvite??'';const[info,setInfo]=useState<{className:string;classId:string}|null>(null),[step,setStep]=useState(0),[name,setName]=useState(''),[roll,setRoll]=useState(''),[consent,setConsent]=useState(false),[faces,setFaces]=useState<Face[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(''),[camera,setCamera]=useState(false),[done,setDone]=useState(false),[automatic,setAutomatic]=useState(false);const video=useRef<HTMLVideoElement>(null),stream=useRef<MediaStream|null>(null),sampling=useRef(false),facesRef=useRef(faces);
useEffect(()=>{facesRef.current=faces},[faces]);useEffect(()=>{if(!invite){setError('Registration will open after shared storage is connected. Please check back shortly.');return;}api('enroll?invite='+encodeURIComponent(invite)).then(setInfo).catch(e=>setError(e.message));return()=>stream.current?.getTracks().forEach(t=>t.stop())},[invite]);
function stop(){setAutomatic(false);stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;setCamera(false)}
useEffect(()=>{if(camera&&video.current){video.current.srcObject=stream.current;video.current.play().catch(()=>setError('Tap the preview to start your camera.'))}},[camera]);
async function openCamera(){setBusy('Opening camera');setError('');try{stream.current=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:1280}},audio:false});setCamera(true)}catch{setError('Allow camera access, or upload face photos below.')}finally{setBusy('')}}
async function capture(){if(sampling.current||!video.current||facesRef.current.length>=30)return;sampling.current=true;setError('');try{const results=await detect(video.current);if(results.length!==1)throw Error('Only your face should be visible.');if(!results[0].usable)throw Error('Move closer, face the light and hold still.');const f=results[0].face;if(facesRef.current.some(o=>o.vector.reduce((n,v,i)=>n+(v-f.vector[i])**2,0)/576<.0015))throw Error('Move your head a little more so we can save a different sample.');setFaces(prev=>[...prev,f].slice(0,30));
}catch(e){setError((e as Error).message)}finally{sampling.current=false}}
useEffect(()=>{if(!automatic)return;const timer=setInterval(()=>{if(facesRef.current.length>=30)setAutomatic(false);else capture()},1100);return()=>clearInterval(timer)},[automatic]);
async function upload(files:File[]){setBusy('Checking photos');setError('');try{const incoming=[...facesRef.current];for(const file of files){if(incoming.length>=30)break;const result=await imageFile(file);if(result.length!==1||!result[0].usable)throw Error(`${file.name}: use one clear, well-lit face.`);const f=result[0].face;if(incoming.some(o=>o.vector.reduce((n,v,i)=>n+(v-f.vector[i])**2,0)/576<.0015))continue;incoming.push(f);}setFaces(incoming);facesRef.current=incoming;}catch(e){setError((e as Error).message)}finally{setBusy('')}}
const guide=faces.length<4?{title:'Look straight at the camera',short:'Straight',icon:null}:faces.length<8?{title:'Slowly turn your head a little left',short:'Left',icon:<ArrowLeft size={18}/>} :faces.length<12?{title:'Slowly turn your head a little right',short:'Right',icon:<ArrowRight size={18}/>} :faces.length<16?{title:'Tilt your chin slightly up',short:'Up',icon:<ArrowUp size={18}/>} :faces.length<20?{title:'Tilt your chin slightly down',short:'Down',icon:<ArrowDown size={18}/>} :{title:'Great — keep moving naturally for extra samples',short:'Complete',icon:<Check size={18}/>};
const guideSteps=[{label:'Straight',icon:<ScanFace size={16}/>},{label:'Left',icon:<ArrowLeft size={16}/>},{label:'Right',icon:<ArrowRight size={16}/>},{label:'Up',icon:<ArrowUp size={16}/>},{label:'Down',icon:<ArrowDown size={16}/>}];const guideIndex=faces.length<4?0:faces.length<8?1:faces.length<12?2:faces.length<16?3:faces.length<20?4:5;
if(done)return <div className="entry-card panel complete"><span className="brand-icon"><Check/></span><h1>You’re all set, {name.split(' ')[0]}.</h1><p>Your registration was sent to your teacher for review. After approval, your samples will help train your class’s attendance model.</p><span className="status green">Submitted successfully</span><p className="muted">You can close this page. Ask your teacher if you need to change your details.</p></div>;
return <div className="entry-layout"><div className="entry-intro"><div className="eyebrow">YOUR CLASSROOM STARTS WITH YOU</div><h1>Enter your<br/>data.</h1><p>Register once. Spend less time on roll call.</p><div className="entry-steps">{['Your details','Face samples','Review & submit'].map((text,i)=><div key={text} className={step===i?'current':''}><span>{i+1}</span><strong>{text}</strong>{step>i&&<Check size={16}/>}</div>)}</div><div className="note"><ShieldCheck size={20}/><span>Only your teacher can review your submission. Face detection runs on your device; accepted samples are sent securely when you submit.</span></div></div><div className="panel entry-form"><span className="badge">{info?.className??'Student registration'}</span><h2>{step===0?'Let’s get to know you.':step===1?'A few clear photos.': 'Check your registration.'}</h2>{error&&<div role="alert" className="alert error">{error}</div>}{busy&&<div className="alert"><LoaderCircle className="spin" size={16}/>{busy}…</div>}
{step===0&&<form onSubmit={e=>{e.preventDefault();setError('');setStep(1)}}><label>Full name<input maxLength={100} autoComplete="name" value={name} onChange={e=>setName(e.target.value)} placeholder="Enter your full name" required/></label><label>SAP ID<input maxLength={40} value={roll} onChange={e=>setRoll(e.target.value)} placeholder="Enter SAP ID" required/></label><label className="consent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)} required/><span>I give permission to store my face samples and use them for attendance in this class. I can ask my teacher to remove them.</span></label><p className="muted">Prefer manual attendance? Contact your teacher.</p><button className="primary full" disabled={!info||!name.trim()||!roll.trim()||!consent}>Continue to face samples <ChevronRight size={17}/></button></form>}
{step===1&&<><p>Keep your face inside the guide and follow the directions. Samples are taken automatically while you move, similar to setting up Face ID.</p><div className="pose-guide"><strong>{guide.title}</strong><span>{faces.length} / 20 minimum · 30 maximum</span><progress value={Math.min(faces.length,20)} max={20}/></div>{camera?<div className="camera-box"><video ref={video} muted autoPlay playsInline/><div aria-live="polite" style={{position:'absolute',top:12,left:12,right:12,zIndex:2,display:'flex',justifyContent:'center',pointerEvents:'none'}}><div style={{display:'inline-flex',alignItems:'center',gap:8,maxWidth:'92%',padding:'9px 13px',borderRadius:999,background:'rgba(16,42,32,.88)',color:'#fff',fontWeight:700,fontSize:13,textAlign:'center',boxShadow:'0 4px 18px rgba(0,0,0,.18)'}}>{guide.icon}{automatic?guide.title:'Press “Start taking samples” and follow the guide'}</div></div><div style={{position:'absolute',left:'50%',top:'48%',transform:'translate(-50%,-50%)',width:'48%',maxWidth:230,aspectRatio:'3 / 4',border:`3px solid ${automatic?'#c8e1bb':'rgba(255,255,255,.72)'}`,borderRadius:'48% 48% 44% 44% / 42% 42% 58% 58%',boxShadow:automatic?'0 0 0 999px rgba(7,30,21,.14),0 0 22px rgba(200,225,187,.35)':'0 0 0 999px rgba(7,30,21,.12)',pointerEvents:'none',zIndex:1}}/><div style={{position:'absolute',left:10,right:10,bottom:64,zIndex:2,display:'grid',gridTemplateColumns:'repeat(5,1fr)',gap:5,pointerEvents:'none'}}>{guideSteps.map((s,i)=><div key={s.label} style={{display:'flex',flexDirection:'column',alignItems:'center',gap:3,padding:'6px 2px',borderRadius:8,background:i===guideIndex?'rgba(200,225,187,.95)':'rgba(16,42,32,.78)',color:i===guideIndex?'#15392d':'#fff',fontSize:9,fontWeight:i===guideIndex?700:500}}>{s.icon}<span>{s.label}</span></div>)}</div><div className="camera-controls"><button className="primary" onClick={()=>setAutomatic(!automatic)} disabled={!!busy||faces.length>=30}>{automatic?'Pause samples':'Start taking samples'}</button><button onClick={stop}>Stop camera</button></div></div>:<button className="primary full" onClick={openCamera} disabled={!!busy}><Camera size={18}/>Open camera</button>}<label className="button full"><Upload size={16}/>Or upload several face photos<input type="file" accept="image/*" multiple disabled={!!busy||automatic} onChange={e=>{const files=Array.from(e.target.files??[]);e.target.value='';upload(files)}}/></label><div className="samples">{faces.map((f,i)=><button key={i} aria-label={`Remove sample ${i+1}`} onClick={()=>setFaces(prev=>prev.filter((_,j)=>j!==i))}><img src={f.image} alt={`Face sample ${i+1}`}/><span>×</span></button>)}</div><button className="primary full" disabled={faces.length<20||!!busy} onClick={()=>{stop();setError('');setStep(2)}}>Review registration <ChevronRight size={17}/></button><button className="text-button" onClick={()=>{stop();setStep(0)}}>Back to details</button></>}
{step===2&&<><div className="registration-review">{faces[0]&&<img src={faces[0].image} alt="Your face sample"/>}<h3>{name}</h3><p>SAP ID {roll} · {info?.className}</p><span className="status green">{faces.length} accepted samples</span></div><p>Your teacher will check your details before adding you to the recognition model.</p><button className="primary full" disabled={!!busy} onClick={async()=>{setBusy('Submitting registration');setError('');try{await api('enroll?invite='+encodeURIComponent(invite),'POST',{name:name.trim(),roll:roll.trim(),faces,consent});setDone(true);setFaces([])}catch(e){setError((e as Error).message)}finally{setBusy('')}}}><Check size={17}/>Submit my registration</button><button className="text-button" disabled={!!busy} onClick={()=>setStep(1)}>Back to samples</button></>}
</div></div>
}
