export type Sample={label:string;vector:number[]};
export type Model={mean:number[];pca:number[][];lda:number[][];templates:Sample[];limits:Record<string,number>;version:string;dimensions:number;trainedAt:string};
const dot=(a:number[],b:number[])=>a.reduce((s,v,i)=>s+v*b[i],0);
const norm=(a:number[])=>Math.sqrt(dot(a,a));
const project=(x:number[],basis:number[][])=>basis.map(b=>dot(x,b));
function eigen(a:number[][]){const n=a.length,m=a.map(r=>[...r]),v=Array.from({length:n},(_,i)=>Array.from({length:n},(_,j)=>+(i===j)));for(let it=0;it<n*n*60;it++){let p=0,q=0,max=0;for(let i=0;i<n;i++)for(let j=i+1;j<n;j++)if(Math.abs(m[i][j])>max){max=Math.abs(m[i][j]);p=i;q=j;}if(max<1e-9)break;const phi=.5*Math.atan2(2*m[p][q],m[q][q]-m[p][p]),c=Math.cos(phi),s=Math.sin(phi);const app=m[p][p],aqq=m[q][q],apq=m[p][q];for(let k=0;k<n;k++)if(k!==p&&k!==q){const kp=m[k][p],kq=m[k][q];m[k][p]=m[p][k]=c*kp-s*kq;m[k][q]=m[q][k]=s*kp+c*kq;}m[p][p]=c*c*app-2*s*c*apq+s*s*aqq;m[q][q]=s*s*app+2*s*c*apq+c*c*aqq;m[p][q]=m[q][p]=0;for(let k=0;k<n;k++){const kp=v[k][p],kq=v[k][q];v[k][p]=c*kp-s*kq;v[k][q]=s*kp+c*kq;}}return m.map((r,i)=>({value:r[i],vector:v.map(row=>row[i])})).sort((a,b)=>b.value-a.value);}
const distance=(a:number[],b:number[])=>Math.sqrt(a.reduce((s,x,i)=>s+(x-b[i])**2,0));
export function features(model:Model,x:number[]){return project(project(x.map((v,i)=>v-model.mean[i]),model.pca),model.lda);}
export function train(samples:Sample[]):Model{
 const labels=[...new Set(samples.map(s=>s.label))];if(labels.length<2)throw Error('Register at least two students before training.');if(labels.some(l=>samples.filter(s=>s.label===l).length<5))throw Error('Each student needs at least five accepted samples.');const d=samples[0].vector.length;if(!d||samples.some(s=>s.vector.length!==d||s.vector.some(x=>!Number.isFinite(x))))throw Error('Invalid training vectors.');
 const mean=Array.from({length:d},(_,i)=>samples.reduce((a,s)=>a+s.vector[i],0)/samples.length),x=samples.map(s=>s.vector.map((v,i)=>v-mean[i])),pca:number[][]=[];const k=Math.min(16,samples.length-labels.length,d);
 for(let c=0;c<k;c++){let b=Array.from({length:d},(_,i)=>Math.sin((i+1)*(c+1)*1.73));for(let it=0;it<24;it++){const y=Array(d).fill(0);for(const row of x){const w=dot(row,b);for(let j=0;j<d;j++)y[j]+=w*row[j];}for(const prev of pca){const w=dot(y,prev);for(let j=0;j<d;j++)y[j]-=w*prev[j];}const len=norm(y);if(len<1e-9)break;b=y.map(t=>t/len);}for(const prev of pca){const w=dot(b,prev);b=b.map((v,j)=>v-w*prev[j]);}const len=norm(b);if(len>1e-7)pca.push(b.map(v=>v/len));}
 const z=x.map(row=>project(row,pca)),n=pca.length,sw=Array.from({length:n},()=>Array(n).fill(0)),sb=Array.from({length:n},()=>Array(n).fill(0));for(const label of labels){const rows=z.filter((_,i)=>samples[i].label===label),mu=Array.from({length:n},(_,i)=>rows.reduce((a,r)=>a+r[i],0)/rows.length);for(let i=0;i<n;i++)for(let j=0;j<n;j++){sb[i][j]+=rows.length*mu[i]*mu[j];sw[i][j]+=rows.reduce((a,r)=>a+(r[i]-mu[i])*(r[j]-mu[j]),0);}}
 const ridge=Math.max(1e-5,sw.reduce((s,r,i)=>s+r[i],0)/n*.02);for(let i=0;i<n;i++)sw[i][i]+=ridge;const white=eigen(sw).map(e=>e.vector.map(v=>v/Math.sqrt(Math.max(e.value,ridge))));const b=white.map(u=>white.map(v=>u.reduce((s,ui,i)=>s+ui*dot(sb[i],v),0)));const lda=eigen(b).slice(0,Math.min(labels.length-1,n)).map(e=>Array.from({length:n},(_,i)=>white.reduce((s,w,j)=>s+w[i]*e.vector[j],0)));
 const model:Model={mean,pca,lda,templates:[],limits:{},version:crypto.randomUUID(),dimensions:d,trainedAt:new Date().toISOString()};model.templates=samples.map(s=>({label:s.label,vector:features(model,s.vector)}));for(const label of labels){const own=model.templates.filter(t=>t.label===label),others=model.templates.filter(t=>t.label!==label);const nearest=own.map((t,i)=>Math.min(...own.filter((_,j)=>j!==i).map(o=>distance(t.vector,o.vector)))).sort((a,b)=>a-b);const impostor=Math.min(...own.flatMap(t=>others.map(o=>distance(t.vector,o.vector))));model.limits[label]=Math.max(1e-6,Math.min(Math.max(nearest[Math.floor((nearest.length-1)*.9)]*2.5,impostor*.15),impostor*.45));}return model;
}
export function predict(model:Model,x:number[]){if(x.length!==model.dimensions)throw Error('Face dimensions do not match model.');const f=features(model,x),scores=Object.keys(model.limits).map(label=>({label,distance:Math.min(...model.templates.filter(t=>t.label===label).map(t=>distance(f,t.vector)))})).sort((a,b)=>a.distance-b.distance);const best=scores[0],ratio=best.distance/Math.max(scores[1]?.distance??Infinity,1e-9);return {...best,accepted:best.distance<=model.limits[best.label]&&ratio<.72,ratio};}
