import {api} from './api';import {config} from './config';
import type {Model} from './model';
export type Face={image:string;vector:number[]};export type Student={id:string;name:string;roll:string;classId:string;faces:Face[]};export type Classroom={id:string;name:string};export type Attendance={studentId:string;name:string;roll:string;status:'present'|'absent';method:'recognition'|'manual';};export type Session={id:string;classId:string;className:string;subject:string;date:string;records:Attendance[];modelVersion?:string;corrections?:{studentId:string;previous:string;next:string;at:string}[]};export type State={classes:Classroom[];students:Student[];sessions:Session[];models:Record<string,Model>};
export const initial:State={classes:[],students:[],sessions:[],models:{}};
function open(){return new Promise<IDBDatabase>((resolve,reject)=>{const r=indexedDB.open('eigenroll',1);r.onupgradeneeded=()=>r.result.createObjectStore('state');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
async function localLoad(){const db=await open();return new Promise<State>((resolve,reject)=>{const tx=db.transaction('state','readonly'),r=tx.objectStore('state').get('workspace');r.onsuccess=()=>resolve(r.result??structuredClone(initial));r.onerror=()=>reject(r.error);tx.oncomplete=()=>db.close();});}
async function localSave(state:State){const db=await open();return new Promise<void>((resolve,reject)=>{const tx=db.transaction('state','readwrite');tx.objectStore('state').put(state,'workspace');tx.oncomplete=()=>{db.close();resolve()};tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error);});}
export function validateBackup(data:unknown):State {const s=data as State;if(!s||!Array.isArray(s.classes)||!Array.isArray(s.students)||!Array.isArray(s.sessions)||!s.models||typeof s.models!=='object')throw Error('Invalid EigenRoll backup.');if(s.classes.some(c=>typeof c.id!=='string'||typeof c.name!=='string')||s.students.some(x=>typeof x.id!=='string'||typeof x.name!=='string'||typeof x.roll!=='string'||!s.classes.some(c=>c.id===x.classId)||!Array.isArray(x.faces)||x.faces.some(f=>typeof f.image!=='string'||!f.image.startsWith('data:image/')||!Array.isArray(f.vector)||f.vector.length!==576||f.vector.some(v=>!Number.isFinite(v)))))throw Error('Backup contains invalid student data.');if(s.sessions.some(x=>typeof x.id!=='string'||typeof x.subject!=='string'||typeof x.date!=='string'||!Array.isArray(x.records)||x.records.some(r=>!['present','absent'].includes(r.status))))throw Error('Backup contains invalid attendance.');for(const m of Object.values(s.models))if(m.dimensions!==576||!Array.isArray(m.mean)||!Array.isArray(m.pca)||!Array.isArray(m.lda)||!Array.isArray(m.templates)||!m.limits)throw Error('Backup contains an invalid model.');return s;}
export function download(name:string,content:string,type='application/json'){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function csv(rows:string[][]){return rows.map(row=>row.map(v=>'"'+(/^[=+\-@\t\r]/.test(v)?"'"+v:v).replaceAll('"','""')+'"').join(',')).join('\r\n');}

const remote=new Map<string,{content:string;revision:number}>();
function entities(state:State){return [...state.classes.map(payload=>({id:'classes:'+payload.id,kind:'classes',payload})),...state.students.map(payload=>({id:'students:'+payload.id,kind:'students',payload})),...state.sessions.map(payload=>({id:'sessions:'+payload.id,kind:'sessions',payload})),...Object.entries(state.models).map(([id,payload])=>({id:'models:'+id,kind:'models',payload}))];}
export async function load():Promise<State>{if(!config.sharedStorage)return localLoad();const state=structuredClone(initial);remote.clear();await Promise.all((['classes','students','sessions','models'] as const).map(async kind=>{for(let offset=0;;offset+=5){const r=await api<{rows:{id:string;payload:any;revision:number}[]}>('workspace?kind='+kind+'&offset='+offset);for(const row of r.rows){remote.set(row.id,{content:JSON.stringify(row.payload),revision:row.revision});if(kind==='models')state.models[row.id.slice(7)]=row.payload;else (state[kind] as unknown[]).push(row.payload);}if(r.rows.length<5)break;}}));return state;}
export async function save(state:State){if(!config.sharedStorage)return localSave(state);const rows=entities(state);for(const row of rows){const content=JSON.stringify(row.payload),previous=remote.get(row.id);if(previous?.content===content)continue;const result=await api<{revision:number}>('workspace','POST',{...row,revision:previous?.revision});remote.set(row.id,{content,revision:result.revision});}for(const [id,previous]of remote){if(rows.some(r=>r.id===id))continue;await api('workspace','DELETE',{id,kind:id.split(':')[0],revision:previous.revision});remote.delete(id);}}

export const loadPreviousBrowserWorkspace=localLoad;
